language: python
python: 2.7

env:
  globals:
    - SOURCE_CONFIG_FILE=${TRAVIS_BUILD_DIR}/tests/config/odoo-travis.cfg

services:
  - postgresql

virtualenv:
  # needed for lxml, lxml installed with pip in the virtualenv gives an
  # error on travis
  system_site_packages: true

addons:
  postgresql: "9.4"
  apt:
    packages:
      - python-lxml # because pip installation is slow

install:
  - pip install flake8 invoke tox

script:
  - tox
